apiVersion: v1
kind: Service
metadata:
  name: netbird-lb
  namespace: netbird
spec:
  type: LoadBalancer
  # IP will be auto-assigned from MetalLB pool (10.0.200.1-250)
  selector:
    app.kubernetes.io/name: netbird-client
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
---
