apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netbird-ingress
  namespace: netbird
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    cert-manager.io/cluster-issuer: letsencrypt-dns
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - netbird.k3s.dahan.house
    secretName: netbird-tls
  rules:
    - host: netbird.k3s.dahan.house
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: netbird
                port:
                  number: 80
---
