apiVersion: v1
kind: Service
metadata:
  name: netbird-management
  namespace: netbird
  labels:
    app.kubernetes.io/name: netbird-management
    app.kubernetes.io/component: management
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: netbird-management
  ports:
    - name: grpc
      port: 33073
      targetPort: 33073
      protocol: TCP
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
---
