apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: netbird-dashboard
  namespace: netbird
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`netbird.k3s.dahan.house`)
      kind: Rule
      services:
        - name: netbird-dashboard
          port: 80
  tls:
    secretName: netbird-dashboard-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: netbird-management-api
  namespace: netbird
spec:
  entryPoints:
    - web
    - websecure
  routes:
    # HTTP API and gRPC routes (same port)
    - match: Host(`netbird-api.k3s.dahan.house`)
      kind: Rule
      services:
        - name: netbird-management
          port: 33073
  tls:
    secretName: netbird-api-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: netbird-signal
  namespace: netbird
spec:
  entryPoints:
    - web
    - websecure
  routes:
    # gRPC Signal routes
    - match: Host(`netbird-signal.k3s.dahan.house`) && PathPrefix(`/signalexchange.SignalExchange/`)
      kind: Rule
      services:
        - name: netbird-signal
          port: 10000
          scheme: h2c
  tls:
    secretName: netbird-signal-tls
---
