apiVersion: v1
kind: Service
metadata:
  name: claude-http
  namespace: claude
  labels:
    app.kubernetes.io/name: claude
spec:
  type: ClusterIP
  ports:
  - name: wetty
    port: 3000
    targetPort: 3000
    protocol: TCP
  - name: code-server
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: claude
