apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: wetty-redirect
  namespace: claude
spec:
  redirectRegex:
    regex: "^(https://claude\\.k3s\\.dahan\\.house)/?$"
    replacement: "${1}/wetty"
    permanent: false
