apiVersion: v1
kind: Secret
metadata:
  name: nautobot-secret
  namespace: nautobot
  labels:
    app.kubernetes.io/name: nautobot
    app.kubernetes.io/component: ipam
type: Opaque
stringData:
  NAUTOBOT_SECRET_KEY: "8zR3m9vK2nX7pQ4wL6tY1hJ5fC0bN8aE9xS2vM4dG7kP3qW6r"
  NAUTOBOT_SUPERUSER_NAME: "admin"
  NAUTOBOT_SUPERUSER_EMAIL: "admin@dahan.house"
  NAUTOBOT_SUPERUSER_PASSWORD: "admin"
  NAUTOBOT_SUPERUSER_API_TOKEN: "0123456789abcdef0123456789abcdef01234567"
  NAUTOBOT_DB_HOST: "postgres.postgres.svc.cluster.local"
  NAUTOBOT_DB_PORT: "5432"
  NAUTOBOT_DB_NAME: "nautobot"
  NAUTOBOT_DB_USER: "nautobot"
  NAUTOBOT_DB_PASSWORD: "nautobot"
  NAUTOBOT_REDIS_HOST: "redis.nautobot.svc.cluster.local"
  NAUTOBOT_REDIS_PORT: "6379"
  NAUTOBOT_REDIS_PASSWORD: ""
  NAUTOBOT_ALLOWED_HOSTS: "*"
