apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nautobot-k3s-dahan-house
  namespace: nautobot
  labels:
    app.kubernetes.io/name: nautobot
    app.kubernetes.io/component: ipam
spec:
  secretName: nautobot-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
  - nautobot.k3s.dahan.house
