---
# Certificate for wildcard *.k3s.dahan.house
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k3s-dahan-house-wildcard
  namespace: kube-system
spec:
  secretName: k3s-dahan-house-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
    - "k3s.dahan.house"
    - "*.k3s.dahan.house"
