apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: rustdesk-hbbs-tcp
  namespace: rustdesk
  labels:
    app: rustdesk-hbbs
spec:
  entryPoints:
    - rustdesk-hbbs
  routes:
    - match: HostSNI(`*`)
      services:
        - name: rustdesk-lb
          port: 21118
