apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: rustdesk-hbbr-tcp
  namespace: rustdesk
  labels:
    app: rustdesk-hbbr
spec:
  entryPoints:
    - rustdesk-hbbr
  routes:
    - match: HostSNI(`*`)
      services:
        - name: rustdesk-relay-lb
          port: 21119
