apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-k3s-dahan-house
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik
spec:
  secretName: authentik-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
  - auth.k3s.dahan.house
---
