apiVersion: v1
kind: Secret
metadata:
  name: newt-credentials
  namespace: newt
type: Opaque
stringData:
  NEWT_ID: "nxst1hz292n6xw4"
  NEWT_SECRET: "qs1ss9oitm0zlf9lrll71elejjp4p2gyeq7p77jzew8xi2kj"
  PANGOLIN_ENDPOINT: "https://pangolin.k3s.dahan.house"
