apiVersion: v1
kind: Secret
metadata:
  name: newt-credentials
  namespace: newt
type: Opaque
stringData:
  NEWT_ID: "dx0w28idc7yorl2"
  NEWT_SECRET: "m8s7pmjp4zso5dhejp4ci2dxyujbdrkxol32wev3v2v6fo9do"
  PANGOLIN_ENDPOINT: "https://pangolin.k3s.dahan.house"
