apiVersion: apps/v1
kind: Deployment
metadata:
  name: newt
  namespace: newt
  labels:
    app: newt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newt
  template:
    metadata:
      labels:
        app: newt
    spec:
      containers:
      - name: newt
        image: fosrl/newt:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: newt-credentials
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      restartPolicy: Always
