apiVersion: v1
kind: Service
metadata:
  name: rancher-lb
  namespace: cattle-system
  labels:
    app.kubernetes.io/name: rancher
    app: rancher
  annotations:
    metallb.universe.tf/allow-shared-ip: "rancher"
spec:
  type: LoadBalancer
  # IP will be auto-assigned from MetalLB pool (10.0.200.1-250)
  selector:
    app: rancher
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
---
