apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rancher-k3s-dahan-house
  namespace: cattle-system
  labels:
    app.kubernetes.io/name: rancher
spec:
  secretName: rancher-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
  - rancher.k3s.dahan.house
---
