apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homer-k3s-dahan-house
  namespace: homer
  labels:
    app.kubernetes.io/name: homer
    app.kubernetes.io/component: dashboard
spec:
  secretName: homer-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
  - homer.k3s.dahan.house
