apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portainer
  namespace: portainer
  labels:
    app.kubernetes.io/name: portainer
    app.kubernetes.io/component: management
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`portainer.k3s.dahan.house`)
      services:
        - name: portainer
          port: 9000
  tls:
    secretName: portainer-tls
