apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portainer-k3s-dahan-house
  namespace: portainer
  labels:
    app.kubernetes.io/name: portainer
    app.kubernetes.io/component: management
spec:
  secretName: portainer-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
  - portainer.k3s.dahan.house
