apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/component: automation
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`home.k3s.dahan.house`)
      services:
        - name: home-assistant
          port: 8123
  tls:
    secretName: home-assistant-tls
