apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-assistant-k3s-dahan-house
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/component: automation
spec:
  secretName: home-assistant-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
  - home.k3s.dahan.house
