apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: netbox
  namespace: netbox
  labels:
    app.kubernetes.io/name: netbox
    app.kubernetes.io/component: ipam
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`netbox.k3s.dahan.house`)
      services:
        - name: netbox
          port: 8080
  tls:
    secretName: netbox-tls
