apiVersion: v1
kind: Service
metadata:
  name: pangolin-api
  namespace: pangolin
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.200.244
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: pangolin
  ports:
  - name: api
    port: 80
    targetPort: 5050
    protocol: TCP
---
