apiVersion: v1
kind: Service
metadata:
  name: pangolin-lb
  namespace: pangolin
  annotations:
    metallb.universe.tf/allow-shared-ip: "pangolin"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.200.242
  selector:
    app.kubernetes.io/name: pangolin
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
---
