apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-oidc
  namespace: vaultwarden
type: Opaque
stringData:
  SSO_CLIENT_ID: "UGSwelihDhR83yFx0pwrzGxsGZCxmpimY4B7ibkH"
  SSO_CLIENT_SECRET: "am8ldLvu2wfjGTQs1OPv66GwgX4ggFbX7ngNBrIcp86jTt4fP4s2zYEdEjA8TbIW3CDnp9lzTVpjPHC0MzLY9f0uZdQZ5nuPhxmdUSkw9cxAX3LLg12BoGWYkJI919hi"
